# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"git": "00_core.ipynb",
         "python": "00_core.ipynb",
         "home": "00_core.ipynb",
         "blogslicer": "00_core.ipynb",
         "file_obj": "00_core.ipynb",
         "df": "00_core.ipynb",
         "df.columns": "00_core.ipynb",
         "Site": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://miklevin.github.io/skite/"

git_url = "https://github.com/miklevin/skite/tree/main/"

def custom_doc_links(name): return None
